import Navbar from "./Navbar";
import Head from 'next/head'
import { Lexend } from '@next/font/google';
import localFont from '@next/font/local'

// Font files can be colocated inside of `pages`
const lexendLocal = localFont({ src: '../public/assets/font/lexend/Lexend-Regular.ttf' })

const lexend = Lexend({
    weight: '100',
})
const Layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>PortoLy</title>
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content="Generated by create next app" />
            </Head>
            <div className={`${lexendLocal.className}`}>
                <Navbar />
                <div className="content container px-3 mx-auto mt-2">
                    {children}
                </div>
            </div>
        </div>
    );
}

export default Layout;