import Navbar from "./Navbar";
import Head from 'next/head'
import { Lexend } from '@next/font/google';

const lexend = Lexend({
    weight: '200',
})
const Layout = ({ children }) => {
    return (
        <main className={lexend.className}>
            <Head>
                <title>PortoLy</title>
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Navbar />
            <div className="content container px-3 mx-auto mt-2">
                {children}
            </div>
        </main>
    );
}

export default Layout;