import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className='text-zinc-500'> Hello EWODFJN</h1>
        <h1> Hello bangkit</h1>
      </main> 

      <footer className="">

      </footer>
    </div>
  )
}
